### ISSUE TITLE
logs

### ISSUE THREAD

**Issue by Mr-omega-alpha** [mt09sp/woolich_log_decoder#3]
Did you get the log files i tried to push. 
Do you have Discord?

**Comment by mt09sp** [comment]
Sorry I can see them but didn't realise they were there. I will look at them tomorrow. Damn that was 4 months ago.

**Comment by Mr-omega-alpha** [comment]
no stress.. and sorry i didnt know how to even use github back then... lol 
i cant even remember what i added,... which logs

**Comment by mt09sp** [comment]
I've just gone through them... The Log file decoder reads them without any issues. All the columns are identical. There's some slight variation in the ETV and TPS calibration calculations but not enough to worry about it.

You can use the log file decoder like I do to filter out data that you may not want to go into autotune like removing gear 1 and 2 logs. Below idle logs and low gear engine braking.

**Comment by Mr-omega-alpha** [comment]
So how far was the AFR read off by? I cant remember the Diameter i put in but length was defienitly 1000.. I run A full akro  system.. Ill have to double chaeck... But my AFR does sho0ot high off throttle because PAIR valve delete, exhaust valve delete.I actually havent done much for AFR... a few changed here and there.. But ive since changed my approach and have gone rather agressiev.. Im glade your decoder will work.. If i export VIA Woolich i get 3-5 data points only and 2hardly any help...and got the same spewll as you./. Legacy.. which makes no senese.. .Because Jo Blow cant tune shit with out data.

What would be nice ( i havent even tried your software) to leave out fields and also tell it to be a , or TAB CSV.. Comma most widely excepted .. Have you tried one of your CSV exports in MegaLog Viewer

**Comment by mt09sp** [comment]
I cannot tell how far the AFR read was off because it was shifted in the woolich software using the settings I have for the mt09sp. So you just have to make sure you put in the correct header dimensions and header length before you read in the file.
Woolich takes those settings and uses them to shift the AFR value. Realistically i would prefer to defer to them on that. They've likely gone to the effort of getting the engineering right with that given that it's an engineering flow issue. I'm not in a position to question their calculations there.

What I will say though is that if it was wrong then the autotune would never work as the afr readings for the cells would always be out and you would end up with afr values that never settle down.

I haven't bothered to load into any other log viewing software. Mostly I wanted it for data analysis rather than viewing. For viewing I can do that in the woolich software.

Did you see the video? https://www.youtube.com/watch?v=QRkKHFEw4xM

**Comment by Mr-omega-alpha** [comment]
Yes i did thats why i replied so quickly! Ahhh i thougght my offset may have been incorrect and thats why it was out a few cells,.. But yes also in which order data is logged can also effect how it lines up, lots of programs have that issue.. What would be good, and im just saying this out aloud here .. is if we could go through the rom .bin file and define maps ourselves,. Ive already managed  to get the .bin files to popen in other software, they use an XML file to list table address and associasted data. Also MY R1 is a 2015 one of the very first.. Youll see how early if you find the VIN :) anyway,.. my ecu connection is K-line protocol

**Comment by mt09sp** [comment]
K-line? And the logger can read it? Looks like i'll be connecting it to the wifes mt03 then.

**Comment by Mr-omega-alpha** [comment]
There are a couple of different types of Woolich Log boxes. mines the Log-Box Can V3.. BUt when i was looking into how to read and write it Trasdata (another program) had the empty pin positions as i wired Woolich harness into as K Lines.

**Comment by mt09sp** [comment]
I have the log Box-D Can v3
I would love to know which of the 8 pins your single kline connector connects to.

![image](https://github.com/user-attachments/assets/5ebdcbea-4fb5-4da6-8847-e6056ec2d912)

**Comment by Mr-omega-alpha** [comment]
Well in the picture below (Left side) is where you connect the Woolich on bike harness to the ECU using same colored wires.. The other side is Dimesport conection to write to ecu.. Dimesport say this needs to opened up and connected directly to PCB to read the ECU.. And this all i can find on this ecu.. The next ECU Yamaha uses is able to be flashed read/write over CAN and dosent require the use of CNF1 or other sinal generation etc etc  Just need CAN H, CAN L, 12v and Ground pins.. 
Ive never been able to find a Wire diagram that lists where it connects in the harness plug to ECU connection.. Nor a proper listinging of the ECU pinout itself.. 

So ive never tried to experiment  past this point...

If you know other wise happy to be educated.. 

![ecuconnections](https://github.com/user-attachments/assets/e601731a-7f72-4c10-9132-9caaadf798f4)

**Comment by mt09sp** [comment]
Thanks for that. I have the luxury with the gen3 mt09sp of being able to just plug directly into the euro5 connector under the seat which being euro5+ compliant means that everything it transmitted on a can bus anyway.

I didn't have to splice anything in.

I do have an MT03 though and it's k-line so I thought I might be able to wire an adapter for it into the logger which is why I was asking. It looks like it might be too big of a task though.

**Comment by Mr-omega-alpha** [comment]
You can read the K line from the Yamaha diagnostic port.. Thats all they use but it will be in HEX i believe. 
Should be 3 pins.. sometimes 4.. Just chuck a Multi meter what ever is not 12v or 0v is K lol..  
What year MT03?

**Comment by mt09sp** [comment]
2017. I've found the connector under the seat and I already have the cables for the ecu 3 pin connector and the additional 4 pin connector for the separate ABS module. My OBDII reader doesn't support k-line so when you mentioned your bike was k-line and you were using the logger I got quite excited that I could do the same.

I just don't know what to connect it to on the woolich logger. The knowledge gap is in which of the 8 woolich logger pins I need to connect the k-line wire to.

**Comment by Mr-omega-alpha** [comment]
Do you have every thing installed on the bike at the moment? 
Do you have a multi Meter? If you have easy access use a strong bit of wire to putt into the back of the conecter to the logbox and from the other end do continuity check.. Then from there we can figure out what we do know, and from that we can learn the unknown.. 
But i have a feeling that the log box aint all its thought to be.. I think its converting voltages as well.. I cant explain it properly but RXD and TXD only use 3.3v...   I think... And its odd that your version is the same and still works the same... Maybe theres a few trick in that box.. which makes sense.. make one that does a couple of tricks.. not 10 that are different...

**Comment by mt09sp** [comment]
I've got a rather extensive electronics lab at home. You can crack open the log box... It's got a TI SN65HVD232 can bus chip on it as well as a silconix DB202B which is basically a logic level shifter. But due to the conformal coating i'm not going to try and trace out the board so the only thing we can safely reverse engineer are the cables.

**Comment by Mr-omega-alpha** [comment]
Hey mate.. How you going? I can not get your decoder to work..  it just creates bin files... All i want is convert to csv file.. How

**Comment by mt09sp** [comment]
It automatically creates a bin file when you open the WRL.

You have to click the export CSV button for it to export the CSV.
The reason for that is that there are options for generating the csv that I use when i'm trying to analyse the files
![image](https://github.com/user-attachments/assets/5e1a1260-c9d6-4671-9f89-d583bf406123)

**Comment by mt09sp** [comment]
Hi Mate, I've done an online ETV adjustor https://divineentanglement.com/woolich/

Is there a chance I could get the XML extract from the data viewer for the R1 files you gave me?

I'd like to make it support the R1. It already does but I need to make sure that the current woolich calculation is correct (correctly wrong) before I tell everyone that it supports R1 files.
